apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: sqlmsi
  name: sqlmsi
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sqlmsi
  template:
    metadata:
      labels:
        run: sqlmsi
        aadpodidbinding: odbcidentity
    spec:
      containers:
      - image: acraccess.azurecr.io/sqlmsi:latest
        name: sqlmsi